resume_from_checkpoint_path: null
ckpt_path: null
result_path: "result"
model_path: "checkpoints/0.1.0-small"
dataset_paths: ["data/train_data/train_lorem.jsonl"]
tokenizer: "dataset/tokenizer.json"
exp_name: "nougat"
train_batch_sizes: [1]
num_workers: 8
val_batch_sizes: [2]
val_batches: 1
input_size: [896, 672]
max_length: 4096
prompt_label_length: 64
max_position_embeddings: 4096
accumulate_grad_batches: 3
window_size: 7
patch_size: 4
embed_dim: 128
hidden_dimension: 1024
num_heads: [4, 8, 16, 32]
encoder_layer: [2, 2, 14, 2]
decoder_layer: 4
align_long_axis: False
num_nodes: 1
seed: 25
lr: 1e-4
min_lr: 1e-6
lr_step: 16
gamma: 0.9996
warmup_steps: 250
num_training_samples_per_epoch: 10000
max_epochs: 300
max_steps: -1
val_check_interval: null
check_val_every_n_epoch: 1
gradient_clip_val: 50
verbose: False
