resume_from_checkpoint_path: null
result_path: "result"
model_path: "checkpoints/0.1.0-small"
ckpt_path: null
dataset_paths: ["data/smiles_pic_cjd/train_std.jsonl"]
tokenizer: "dataset/tokenizer.json"
exp_name: "smiles"
train_batch_sizes: [64]
num_workers: 8
val_batch_sizes: [128]
val_batches: 1
input_size: [448, 448]
image_embedding_size: [14, 14]
max_length: 128
prompt_label_length: 64
max_position_embeddings: 128
accumulate_grad_batches: 3
window_size: 7
patch_size: 4
embed_dim: 16
hidden_dimension: 128
num_heads: [4, 8, 16, 32]
encoder_layer: [2, 2, 14, 2]
decoder_layer: 4
align_long_axis: False
num_nodes: 1
seed: 25
lr: 1e-4
min_lr: 7.5e-6
lr_step: 16
gamma: 0.9996
warmup_steps: 250
num_training_samples_per_epoch: 10000
max_epochs: 30
max_steps: -1
val_check_interval: null
check_val_every_n_epoch: 1
gradient_clip_val: 0.5
verbose: False
